- name: paquets nécessaires
  import_tasks: install_prereqs.yml

- name: MariaDB
  import_tasks: setup_mariadb.yml

- name: WordPress
  import_tasks: setup_wordpress.yml

- name: Apache webserver
  import_tasks: setup_webserver.yml