- name: "Démarrer et activer le service MariaDB"
  ansible.builtin.service:
    name: "{{ services[ansible_distribution | lower].database | default('mariadb') }}"
    state: started
    enabled: yes

- name: "Définir mot de passe root MariaDB si pas encore défini"
  community.mysql.mysql_user:
    name: root
    host_all: yes

    password: "{{ mariadb_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  become: yes

- name: "Créer la base de données pour WordPress"
  community.mysql.mysql_db:
    name: "{{ wordpress_db_name }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  become: yes

- name: "Créer l'utilisateur de la base de données pour WordPress"
  community.mysql.mysql_user:
    name: "{{ wordpress_db_user }}"
    password: "{{ wordpress_db_password }}"
    priv: "{{ wordpress_db_name }}.*:ALL"
    state: present
    host: "localhost"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  become: yes