---
- name: "Start and enable MariaDB service"
  ansible.builtin.service:
    name: "{{ db_service }}"
    state: started
    enabled: yes

- name: "Create the WordPress database"
  community.mysql.mysql_db:
    name: "{{ wp_db_name }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock # Plus sûr que user/pass
  become: yes

- name: "Create the WordPress database user"
  community.mysql.mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    host: "{{ wp_db_host }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  become: yes
  # no_log: true # Décommenter pour ne pas afficher le mot de passe dans les logs